const constant = {
  SET_PAGE_LENGTH: 'SET_PAGE_LENGTH',
  NEXT_PAGE: 'NEXT_PAGE',
  PREVIOUS_PAGE: 'PREVIOUS_PAGE',
  SET_PAGE: 'SET_PAGE',
  SET_FRONT_ACTIVE: 'IS_FRONT_ACTIVE',
  SET_BACK_ACTIVE: 'IS_BACK_ACTIVE',
  ADD_STOP_PAGE: 'ADD_STOP_PAGE',
  ADD_START_PAGE: 'ADD_START_PAGE',
  ADD_STOP_PAGE_MOBILE: 'ADD_STOP_PAGE_MOBILE',
  ADD_START_PAGE_MOBILE: 'ADD_START_PAGE_MOBILE',
  SET_DETAIL_PAGE: 'SET_DETAIL_PAGE'
}

export default constant
